"""Desktop front end: change a number, see what it does to the aeroplane.

    python -m dbf2027.gui          or      python dbf_gui.py

Tkinter only, because tkinter ships with Python and the rest of this
project has no dependencies either.  The charts are drawn on a plain
Canvas from the geometry in `plots.py`; there is no matplotlib.

Layout
------
Left is input, split three ways on purpose:

  * **Setup** - which design is under test, in what weather, scored
    against what.  There are no design FIELDS here.  The aeroplane is a
    single piece of state that a search or `Load...` sets, named by a
    one-line caption that also says where it came from.  An earlier
    version had the full design form here and the Report tab restated
    every one of its thirteen values, which meant the same numbers in two
    places with nothing saying which was authoritative.
  * **Search space** - the ranges `Run search` explores, and the only
    design input on the left.  These were hard-coded in `DesignSpace`
    and unreachable, so a search silently ignored the form.
  * **Advanced** - every remaining number in `Rules`, `Course` and
    `BuildStandard`, generated by walking those dataclasses.  Because it
    is generated, a field added to the model shows up here automatically
    rather than being quietly unreachable.

Right is output, and it is the only place the design is read back: the
full dossier, a dimensions table, the charts, a scale three-view, the
scoring arithmetic, the rules matrix and the function catalogue.

Threading
---------
Evaluating one design takes ~100 ms, which is fast enough to do inline.
A search takes minutes, so it runs on a worker thread and reports back
through a queue that the Tk main loop polls.  Tk is not thread-safe, so
**the worker never touches a widget** - it only puts text on the queue.
"""
from __future__ import annotations

import io
import json
import os
import queue
import threading
import traceback
from contextlib import redirect_stdout
from dataclasses import fields, replace
from typing import Any, Callable, Dict, List, Optional, Tuple

import tkinter as tk
from tkinter import filedialog, messagebox, ttk

from . import plots
from .aircraft import Aircraft, Design
from .catalogue import as_text as catalogue_text, collect as catalogue_collect
from .components import (AIRFOILS, CATALOGUES, CATALOGUES_BY_KEY, MOTORS,
                         PACKS, PROPS, add_user_entry, is_user_entry,
                         reload_catalogues, remove_user_entry, user_csv_path)
from .config import BuildStandard, Config, Environment, Rules
from .optimizer import DesignSpace, SearchSettings, evaluate_design, optimise
from .report import print_bom, print_design_report
from .scoring import evaluate_scores, score_explanation_text
from .units import KG2LB, LB2KG

BG = "#f4f6f9"
MONO = ("Consolas", 9)
HEAD = ("Segoe UI", 10, "bold")
BODY = ("Segoe UI", 9)


# ==========================================================================
# Small helpers
# ==========================================================================
def capture(fn: Callable, *args, **kw) -> str:
    """Run something that prints, and give back what it printed."""
    buf = io.StringIO()
    with redirect_stdout(buf):
        fn(*args, **kw)
    return buf.getvalue()


class Field:
    """One labelled entry box bound to a value of a known type."""

    def __init__(self, parent, row: int, label: str, value: Any,
                 kind: type, tip: str = "", width: int = 12):
        self.kind = kind
        self.name = label
        ttk.Label(parent, text=label, font=BODY).grid(
            row=row, column=0, sticky="w", padx=(6, 4), pady=1)
        self.var = tk.StringVar(value=self._fmt(value))
        e = ttk.Entry(parent, textvariable=self.var, width=width, font=BODY)
        e.grid(row=row, column=1, sticky="ew", padx=(0, 6), pady=1)
        self.entry = e
        if tip:
            ttk.Label(parent, text=tip, font=("Segoe UI", 8),
                      foreground="#666").grid(row=row, column=2, sticky="w",
                                              padx=(0, 6))

    @staticmethod
    def _fmt(v: Any) -> str:
        if isinstance(v, float):
            if v != v or v in (float("inf"), float("-inf")):
                return str(v)
            return ("%.6g" % v)
        return str(v)

    def get(self) -> Any:
        raw = self.var.get().strip()
        if self.kind is bool:
            return raw.lower() in ("1", "true", "yes", "on")
        if self.kind is int:
            return int(float(raw))
        if self.kind is float:
            return float(raw)
        return raw

    def set(self, v: Any) -> None:
        self.var.set(self._fmt(v))


class Combo:
    """A labelled read-only dropdown."""

    def __init__(self, parent, row: int, label: str, values: List[str],
                 value: str, width: int = 22):
        ttk.Label(parent, text=label, font=BODY).grid(
            row=row, column=0, sticky="w", padx=(6, 4), pady=1)
        self.var = tk.StringVar(value=value)
        cb = ttk.Combobox(parent, textvariable=self.var, values=values,
                          state="readonly", width=width, font=BODY)
        cb.grid(row=row, column=1, columnspan=2, sticky="ew",
                padx=(0, 6), pady=1)
        self.widget = cb

    def get(self) -> str:
        return self.var.get()

    def set(self, v: str) -> None:
        self.var.set(v)


def section(parent, text: str, row: int) -> None:
    ttk.Label(parent, text=text, font=HEAD).grid(
        row=row, column=0, columnspan=3, sticky="w", pady=(10, 2), padx=6)
    ttk.Separator(parent, orient="horizontal").grid(
        row=row + 1, column=0, columnspan=3, sticky="ew", padx=6)


# ==========================================================================
# Chart canvas
# ==========================================================================
class ChartCanvas(tk.Canvas):
    """Draws a `plots.Chart`, and redraws itself when the window resizes."""

    def __init__(self, parent, **kw):
        super().__init__(parent, background="white", highlightthickness=0,
                         **kw)
        self.chart: Optional[plots.Chart] = None
        self._retries = 0
        self.bind("<Configure>", lambda e: self.redraw())

    def _retry(self) -> None:
        if self._retries < 3:
            self._retries += 1
            self.redraw()

    def show(self, chart: Optional[plots.Chart]) -> None:
        self.chart = chart
        self.redraw()

    def redraw(self) -> None:
        self.delete("all")
        w, h = self.winfo_width(), self.winfo_height()
        if w < 60 or h < 60:
            # The tab this canvas lives on has not been laid out yet, so
            # there is nothing to draw into.  Switching to the tab fires
            # <Configure> and brings us back here; the idle retry covers
            # the case where it does not.
            self.after_idle(self._retry)
            return
        ch = self.chart
        if ch is None:
            self.create_text(w // 2, h // 2, text="Evaluate a design first",
                             fill="#999", font=BODY)
            return
        self._retries = 0
        m = plots.Mapper(ch, w, h)
        self.create_text(w // 2, 16, text=ch.title, font=HEAD, fill="#222")

        # ---- grid and ticks ----
        xt = plots.nice_ticks(m.x0, m.x1)
        yt = plots.nice_ticks(m.y0, m.y1)
        xstep = (xt[1] - xt[0]) if len(xt) > 1 else 1.0
        ystep = (yt[1] - yt[0]) if len(yt) > 1 else 1.0
        for t in xt:
            x = m.px(t)
            self.create_line(x, m.top, x, m.bottom, fill="#ecf0f4")
            self.create_text(x, m.bottom + 12,
                             text=plots.tick_label(t, xstep),
                             font=("Segoe UI", 8), fill="#555")
        for t in yt:
            y = m.py(t)
            self.create_line(m.left, y, m.right, y, fill="#ecf0f4")
            self.create_text(m.left - 6, y, text=plots.tick_label(t, ystep),
                             anchor="e", font=("Segoe UI", 8), fill="#555")
        self.create_rectangle(m.left, m.top, m.right, m.bottom,
                              outline="#b9c2cc")
        self.create_text((m.left + m.right) // 2, m.bottom + 30,
                         text=ch.x_label, font=BODY, fill="#333")
        self.create_text(14, (m.top + m.bottom) // 2, text=ch.y_label,
                         angle=90, font=BODY, fill="#333")

        # ---- horizontal rules ----
        for value, label, colour in ch.h_lines:
            if not (m.y0 <= value <= m.y1):
                continue
            y = m.py(value)
            self.create_line(m.left, y, m.right, y, fill=colour,
                             dash=(3, 3), width=1)
            self.create_text(m.right - 4, y - 7, text=label, anchor="e",
                             font=("Segoe UI", 8), fill=colour)

        # ---- series ----
        for s in ch.series:
            pts = m.points(s.xs, s.ys)
            if len(pts) >= 4:
                self.create_line(*pts, fill=s.colour, width=s.width,
                                 dash=s.dash or None, smooth=False)

        # ---- legend, top-left inside the frame ----
        ly = m.top + 8
        for s in ch.series:
            self.create_line(m.left + 10, ly, m.left + 34, ly,
                             fill=s.colour, width=s.width,
                             dash=s.dash or None)
            self.create_text(m.left + 40, ly, text=s.label, anchor="w",
                             font=("Segoe UI", 8), fill="#333")
            ly += 14
        if ch.footnote:
            self.create_text(m.left, h - 6, text=ch.footnote, anchor="w",
                             font=("Segoe UI", 8), fill="#777")


class ThreeViewCanvas(tk.Canvas):
    """Plan and side views, drawn to a common scale with a metre rule."""

    def __init__(self, parent, **kw):
        super().__init__(parent, background="white", highlightthickness=0,
                         **kw)
        self.data: Optional[Tuple] = None
        self.span_in = 0.0
        self.length_in = 0.0
        self._retries = 0
        self.bind("<Configure>", lambda e: self.redraw())

    def _retry(self) -> None:
        if self._retries < 3:
            self._retries += 1
            self.redraw()

    def show(self, ac) -> None:
        self.data = plots.three_view(ac) if ac is not None else None
        self.span_in = ac.wing.span_m * 39.3701 if ac is not None else 0.0
        self.length_in = (ac.body.fuse_length_m * 39.3701
                          if ac is not None else 0.0)
        self.redraw()

    def _dim_h(self, y: float, x0: float, x1: float, text: str) -> None:
        """A horizontal dimension line with ticks and a centred label."""
        self.create_line(x0, y, x1, y, fill="#888", arrow="both")
        for x in (x0, x1):
            self.create_line(x, y - 4, x, y + 4, fill="#888")
        self.create_text((x0 + x1) / 2, y + 10, text=text,
                         font=("Segoe UI", 8), fill="#666")

    def _dim_v(self, x: float, y0: float, y1: float, text: str) -> None:
        self.create_line(x, y0, x, y1, fill="#888", arrow="both")
        for y in (y0, y1):
            self.create_line(x - 4, y, x + 4, y, fill="#888")
        self.create_text(x - 8, (y0 + y1) / 2, text=text, angle=90,
                         font=("Segoe UI", 8), fill="#666")

    def redraw(self) -> None:
        self.delete("all")
        w, h = self.winfo_width(), self.winfo_height()
        if w < 80 or h < 80:
            self.after_idle(self._retry)
            return
        if self.data is None:
            self.create_text(w // 2, h // 2, text="Evaluate a design first",
                             fill="#999", font=BODY)
            return
        self._retries = 0
        plan, side, _ext = self.data
        pad = 26
        panel_h = (h - 3 * pad) // 2

        def extent(shapes):
            xs = [p[0] for s in shapes for p in s.points]
            ys = [p[1] for s in shapes for p in s.points]
            return min(xs), max(xs), min(ys), max(ys)

        # one scale for both views, so they are comparable
        scales = []
        for shapes, ph in ((plan, panel_h), (side, panel_h)):
            x0, x1, y0, y1 = extent(shapes)
            scales.append(min((w - 2 * pad) / max(x1 - x0, 1e-6),
                              ph / max(y1 - y0, 1e-6)))
        scale = min(scales) * 0.92

        for idx, (shapes, title) in enumerate(((plan, "PLAN"),
                                               (side, "SIDE"))):
            x0, x1, y0, y1 = extent(shapes)
            oy = pad + idx * (panel_h + pad)
            cx = pad + ((w - 2 * pad) - (x1 - x0) * scale) / 2
            cy = oy + (panel_h - (y1 - y0) * scale) / 2
            self.create_text(pad, oy - 10, text=title, anchor="w",
                             font=("Segoe UI", 8, "bold"), fill="#666")
            for sh in shapes:
                pts = []
                for px, py in sh.points:
                    pts.extend((cx + (px - x0) * scale,
                                cy + (py - y0) * scale))
                if len(pts) < 4:
                    continue
                if sh.fill and len(pts) >= 6:
                    self.create_polygon(*pts, fill=sh.fill,
                                        outline=sh.outline, width=sh.width)
                else:
                    self.create_line(*pts, fill=sh.outline, width=sh.width)

        # ---- dimension callouts on the plan view ----
        x0p, x1p, y0p, y1p = extent(plan)
        oy = pad
        cxp = pad + ((w - 2 * pad) - (x1p - x0p) * scale) / 2
        cyp = oy + (panel_h - (y1p - y0p) * scale) / 2
        self._dim_v(cxp - 10, cyp, cyp + (y1p - y0p) * scale,
                    "span %.0f in" % (self.span_in or 0))
        self._dim_h(cyp + (y1p - y0p) * scale + 12,
                    cxp, cxp + (x1p - x0p) * scale,
                    "length %.0f in" % (self.length_in or 0))

        # scale bar
        bar_m = 0.5
        while bar_m * scale > (w - 2 * pad) * 0.35:
            bar_m *= 0.5
        bx, by = pad, h - 10
        self.create_line(bx, by, bx + bar_m * scale, by, fill="#333", width=2)
        self.create_line(bx, by - 4, bx, by + 4, fill="#333")
        self.create_line(bx + bar_m * scale, by - 4,
                         bx + bar_m * scale, by + 4, fill="#333")
        self.create_text(bx + bar_m * scale + 8, by,
                         text="%.2f m  (%.1f in)" % (bar_m, bar_m * 39.3701),
                         anchor="w", font=("Segoe UI", 8), fill="#333")


# ==========================================================================
# The application
# ==========================================================================
class App(ttk.Frame):
    def __init__(self, master: tk.Tk):
        super().__init__(master, padding=6)
        master.title("DBF 2026-27 optimiser")
        master.geometry("1480x920")
        master.minsize(1100, 700)
        self.pack(fill="both", expand=True)

        self.cfg = Config()
        self.aircraft: Optional[Aircraft] = None
        self.design: Optional[Design] = None
        self.search_q: "queue.Queue[Tuple[str, Any]]" = queue.Queue()
        self.search_thread: Optional[threading.Thread] = None
        self._search_header = ""
        self._after_ids: List[str] = []

        pane = ttk.PanedWindow(self, orient="horizontal")
        pane.pack(fill="both", expand=True)
        left = ttk.Frame(pane, width=430)
        right = ttk.Frame(pane)
        pane.add(left, weight=0)
        pane.add(right, weight=1)

        self._build_inputs(left)
        self._build_outputs(right)
        self._build_statusbar()
        d0, src0 = self._opening_design_and_source()
        self.write_design(d0, src0)
        self._after_ids.append(self.after(120, self._poll_search))
        master.protocol("WM_DELETE_WINDOW", self._close)
        self.evaluate()

    def _close(self) -> None:
        """Cancel pending timers before the widgets go away.

        `after` callbacks outlive the window otherwise, and Tk prints
        "invalid command name" for each one that fires into a destroyed
        widget - which is noise during a search the user closes early.
        """
        for aid in self._after_ids:
            try:
                self.after_cancel(aid)
            except tk.TclError:
                pass
        self._after_ids.clear()
        self.winfo_toplevel().destroy()

    # ------------------------------------------------------------------
    # Input side
    # ------------------------------------------------------------------
    def _build_inputs(self, parent) -> None:
        nb = ttk.Notebook(parent)
        nb.pack(fill="both", expand=True)
        setup = ttk.Frame(nb)
        search = ttk.Frame(nb)
        advanced = ttk.Frame(nb)
        nb.add(setup, text="Setup")
        nb.add(search, text="Search space")
        nb.add(advanced, text="Advanced")
        self._build_setup(setup)
        self._build_search_space(search)
        self._build_advanced(advanced)

        bar = ttk.Frame(parent)
        bar.pack(fill="x", pady=(6, 0))
        ttk.Button(bar, text="Evaluate", command=self.evaluate).pack(
            side="left", padx=2)
        ttk.Button(bar, text="Load...", command=self.load_design).pack(
            side="left", padx=2)
        ttk.Button(bar, text="Save...", command=self.save_design).pack(
            side="left", padx=2)
        ttk.Button(bar, text="Defaults", command=self.reset_defaults).pack(
            side="left", padx=2)

        bar2 = ttk.Frame(parent)
        bar2.pack(fill="x", pady=(4, 0))
        ttk.Label(bar2, text="Search:", font=BODY).pack(side="left", padx=4)
        self.search_mode = tk.StringVar(value="quick")
        ttk.Combobox(bar2, textvariable=self.search_mode, state="readonly",
                     width=10, font=BODY,
                     values=["quick", "default", "thorough"]).pack(side="left")
        self.search_btn = ttk.Button(bar2, text="Run search",
                                     command=self.run_search)
        self.search_btn.pack(side="left", padx=4)
        self.stop_flag = threading.Event()

    @staticmethod
    def _opening_design_and_source() -> Tuple[Design, str]:
        """The design the window opens on, and where it came from."""
        d = App._opening_design()
        src = ("examples/optimised_v1.json" if d.pop("_from_file", False)
               else "built-in fallback")
        span = d["span_m"]
        return (Design(span_m=span, chord_m=span / d["aspect_ratio"],
                       airfoil=d["airfoil"], motor=d["motor"],
                       prop=d["prop"], n_motors=d["n_motors"],
                       pack=d["pack"], n_systems=d["n_systems"],
                       sensor_mass_kg=d["sensor_mass_kg"],
                       n_simulators=d["n_simulators"],
                       sensor_m3_kg=d["sensor_m3_kg"],
                       drop_height_in=d["drop_height_in"]), src)

    @staticmethod
    def _opening_design() -> Dict[str, Any]:
        """The design the window opens on.

        Read from examples/optimised_v1.json when it is there, so the GUI
        opens on whatever the last search actually recommended.  Hard
        coding it here means the opening state silently becomes a stale
        claim about what a good aeroplane looks like: these defaults were
        the optimum before the rules pass, and they were not the optimum
        after it.
        """
        fallback = {"airfoil": "SD7062", "span_m": 1.55, "aspect_ratio": 5.74,
                    "taper": 1.0, "motor": "COBRA_C4120_12",
                    "prop": "APC_12x8", "n_motors": 1,
                    "pack": "GA_6S3300_60C", "n_systems": 1,
                    "sensor_mass_kg": 0.9, "n_simulators": 3,
                    "sensor_m3_kg": 0.9, "drop_height_in": 60}
        here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        path = os.path.join(here, "examples", "optimised_v1.json")
        try:
            with open(path, encoding="utf-8") as fh:
                d = json.load(fh)
        except (OSError, ValueError):
            return fallback
        out = dict(fallback)
        out["_from_file"] = True
        out.update({k: v for k, v in d.items() if k in fallback})
        if d.get("chord_m"):
            out["aspect_ratio"] = d["span_m"] / d["chord_m"]
        if not d.get("sensor_m3_kg"):
            out["sensor_m3_kg"] = d.get("sensor_mass_kg", 0.9)
        return out

    def _build_setup(self, parent) -> None:
        """Which design, flown in what weather, scored against what.

        There are no design fields here.  The aeroplane itself comes from
        a search or from a file, and the Report tab is where you read it:
        having span, airfoil, motor and the rest as controls as well meant
        the same thirteen numbers appeared twice with nothing saying which
        was authoritative.
        """
        canvas, frame = self._scrollable(parent)
        r = 0
        section(frame, "Design under test", r); r += 2
        self.design_label = ttk.Label(
            frame, text="", font=("Segoe UI", 9), foreground="#1c2430",
            wraplength=352, justify="left")
        self.design_label.grid(row=r, column=0, columnspan=3, sticky="w",
                               padx=6, pady=(2, 0))
        r += 1
        self.design_source = ttk.Label(
            frame, text="", font=("Segoe UI", 8), foreground="#666",
            wraplength=352, justify="left")
        self.design_source.grid(row=r, column=0, columnspan=3, sticky="w",
                                padx=6, pady=(0, 4))
        r += 1
        ttk.Label(frame,
                  text="Run search replaces it with the winner; Load... "
                       "reads one from JSON. Every number describing it is "
                       "in the Report, Dimensions and Score tabs.",
                  font=("Segoe UI", 8), foreground="#666",
                  wraplength=352, justify="left").grid(
                      row=r, column=0, columnspan=3, sticky="w", padx=6)
        r += 1

        section(frame, "Conditions on the day", r); r += 2
        self.f_wind = Field(frame, r, "wind", 4.5, float, "m/s"); r += 1
        self.f_alt = Field(frame, r, "field elevation", 0.0, float,
                           "m"); r += 1
        self.f_temp = Field(frame, r, "temperature", 15.0, float,
                            "deg C"); r += 1
        self.f_rho = Field(frame, r, "air density", 1.225, float,
                           "kg/m3"); r += 1
        self.rho_note = ttk.Label(frame, text="", font=("Segoe UI", 8),
                                  foreground="#2f6fdb", wraplength=352,
                                  justify="left")
        self.rho_note.grid(row=r, column=0, columnspan=3, sticky="w",
                           padx=6, pady=(0, 2))
        r += 1
        # Density is what every lift, drag and propeller calculation
        # actually uses; elevation and temperature are only a way of
        # arriving at it.  Editing either recomputes it, and typing a
        # density directly overrides them - which is what you want when
        # someone has read one off a weather station at the field.
        for fld in (self.f_alt, self.f_temp):
            fld.entry.bind("<KeyRelease>", lambda e: self._sync_density())
            fld.entry.bind("<FocusOut>", lambda e: self._sync_density())
        self.f_rho.entry.bind("<KeyRelease>",
                              lambda e: self._update_density_note())
        self._sync_density()
        ttk.Label(frame,
                  text="These DO apply to the loaded design: change one "
                       "and press Evaluate to see how it copes.",
                  font=("Segoe UI", 8), foreground="#666",
                  wraplength=352, justify="left").grid(
                      row=r, column=0, columnspan=3, sticky="w",
                      padx=6, pady=(2, 0))
        r += 1

        section(frame, "Scoring", r); r += 2
        self.f_norm = Combo(frame, r, "normalisation", ["self", "field"],
                            "field"); r += 1
        self.f_fm2 = Field(frame, r, "field best M2", 0.060, float,
                           "lb/s"); r += 1
        self.f_fm3 = Field(frame, r, "field best M3", 22.0, float,
                           "lap*lb"); r += 1
        self.f_fmg = Field(frame, r, "field best GM", 120.0, float,
                           "lb*in"); r += 1
        ttk.Label(frame, text="A single design cannot be self-normalised "
                              "- it would score 1.0 on every ratio by "
                              "definition - so Evaluate always uses the "
                              "estimates above. A search uses whichever "
                              "you pick here, and writes its own bests "
                              "back into them when it finishes.",
                  font=("Segoe UI", 8), foreground="#666", wraplength=352,
                  justify="left").grid(row=r, column=0, columnspan=3,
                                       sticky="w", padx=6, pady=(4, 8))
        frame.columnconfigure(1, weight=1)

    def _build_search_space(self, parent) -> None:
        """What `Run search` is allowed to try.

        These are the only values the search reads from the form.  They
        were previously hard-coded in `DesignSpace` and unreachable, so
        pressing Run search explored a span range the user could neither
        see nor change - while the span box on the Normal tab, which
        looked like it should matter, was ignored.
        """
        canvas, frame = self._scrollable(parent)
        sp = DesignSpace()
        rr = cfg_rules = Config().rules
        ttk.Label(frame,
                  text="The ranges Run search explores. Narrow them to "
                       "steer the search; widen them to let it roam. The "
                       "Normal tab has no effect on a search.",
                  font=("Segoe UI", 8), foreground="#666",
                  wraplength=352, justify="left").grid(
                      row=0, column=0, columnspan=3, sticky="w",
                      padx=6, pady=(6, 2))
        r = 1
        section(frame, "Wing", r)
        r += 2
        self.sp_span_lo = Field(frame, r, "span min", sp.span_bounds[0],
                                float, "m"); r += 1
        self.sp_span_hi = Field(frame, r, "span max", sp.span_bounds[1],
                                float, "capped by the 6 ft rule"); r += 1
        self.sp_ar_lo = Field(frame, r, "aspect ratio min",
                              sp.ar_bounds[0], float, ""); r += 1
        self.sp_ar_hi = Field(frame, r, "aspect ratio max",
                              sp.ar_bounds[1], float, ""); r += 1
        self.sp_taper_lo = Field(frame, r, "taper min", sp.taper_bounds[0],
                                 float, "floored: no tip-stall term"); r += 1
        self.sp_taper_hi = Field(frame, r, "taper max", sp.taper_bounds[1],
                                 float, ""); r += 1

        section(frame, "Payload", r)
        r += 2
        self.sp_sensor_lo = Field(frame, r, "sensor min",
                                  rr.sensor_mass_min_kg, float, "kg"); r += 1
        self.sp_sensor_hi = Field(frame, r, "sensor max",
                                  rr.sensor_mass_max_kg, float, "kg"); r += 1
        self.sp_m3_lo = Field(frame, r, "M3 fraction min",
                              sp.m3_frac_bounds[0], float,
                              "of declared max"); r += 1
        self.sp_m3_hi = Field(frame, r, "M3 fraction max",
                              sp.m3_frac_bounds[1], float, ""); r += 1
        self.sp_drop_lo = Field(frame, r, "drop height min",
                                sp.drop_height_bounds[0], float, "in"); r += 1
        self.sp_drop_hi = Field(frame, r, "drop height max",
                                sp.drop_height_bounds[1], float,
                                "max 60 by rule"); r += 1

        section(frame, "Propulsion layouts", r)
        r += 2
        self.sp_motors = Field(frame, r, "motor counts",
                               ",".join(str(v) for v in sp.motor_counts),
                               str, "max 2 by rule"); r += 1
        self.sp_systems = Field(frame, r, "propulsion systems",
                                ",".join(str(v) for v in sp.system_counts),
                                str, "one pack each"); r += 1
        ttk.Label(frame,
                  text="Airfoils (%d), motors (%d), propellers (%d) and "
                       "battery packs (%d) are searched in full from the "
                       "catalogues. Edit components.py or load a CSV to "
                       "change what is on the shelf."
                       % (len(sp.airfoils), len(sp.motors), len(sp.props),
                          len(sp.packs)),
                  font=("Segoe UI", 8), foreground="#666",
                  wraplength=352, justify="left").grid(
                      row=r, column=0, columnspan=3, sticky="w",
                      padx=6, pady=(8, 4))
        r += 1
        ttk.Button(frame, text="Reset search space",
                   command=self.reset_search_space).grid(
                       row=r, column=0, columnspan=2, sticky="w",
                       padx=6, pady=4)
        frame.columnconfigure(1, weight=1)

    def read_space(self) -> DesignSpace:
        """Build the DesignSpace the search will actually use."""
        def ints(text, fallback):
            out = []
            for part in str(text).split(","):
                part = part.strip()
                if part:
                    try:
                        out.append(int(float(part)))
                    except ValueError:
                        pass
            return out or fallback

        sp = DesignSpace()
        sp.span_bounds = (self.sp_span_lo.get(), self.sp_span_hi.get())
        sp.ar_bounds = (self.sp_ar_lo.get(), self.sp_ar_hi.get())
        sp.taper_bounds = (self.sp_taper_lo.get(), self.sp_taper_hi.get())
        sp.sensor_bounds = (self.sp_sensor_lo.get(), self.sp_sensor_hi.get())
        sp.m3_frac_bounds = (self.sp_m3_lo.get(), self.sp_m3_hi.get())
        sp.drop_height_bounds = (self.sp_drop_lo.get(), self.sp_drop_hi.get())
        sp.motor_counts = ints(self.sp_motors.get(), [1, 2])
        sp.system_counts = ints(self.sp_systems.get(), [1, 2])
        return sp

    def reset_search_space(self) -> None:
        sp, rr = DesignSpace(), Config().rules
        for fld, val in ((self.sp_span_lo, sp.span_bounds[0]),
                         (self.sp_span_hi, sp.span_bounds[1]),
                         (self.sp_ar_lo, sp.ar_bounds[0]),
                         (self.sp_ar_hi, sp.ar_bounds[1]),
                         (self.sp_taper_lo, sp.taper_bounds[0]),
                         (self.sp_taper_hi, sp.taper_bounds[1]),
                         (self.sp_sensor_lo, rr.sensor_mass_min_kg),
                         (self.sp_sensor_hi, rr.sensor_mass_max_kg),
                         (self.sp_m3_lo, sp.m3_frac_bounds[0]),
                         (self.sp_m3_hi, sp.m3_frac_bounds[1]),
                         (self.sp_drop_lo, sp.drop_height_bounds[0]),
                         (self.sp_drop_hi, sp.drop_height_bounds[1])):
            fld.set(val)
        self.sp_motors.set(",".join(str(v) for v in sp.motor_counts))
        self.sp_systems.set(",".join(str(v) for v in sp.system_counts))
        self.status.set("search space reset to defaults")

    def _build_advanced(self, parent) -> None:
        canvas, frame = self._scrollable(parent)
        ttk.Label(frame, text="Every remaining number in the model. These "
                              "are generated from the Rules and "
                              "BuildStandard dataclasses, so nothing can "
                              "be silently unreachable.",
                  font=("Segoe UI", 8), foreground="#666", wraplength=352,
                  justify="left").grid(row=0, column=0, columnspan=3,
                                       sticky="w", padx=6, pady=(4, 2))
        self.adv: Dict[Tuple[str, str], Field] = {}
        r = 1
        for owner, obj, title in (("rules", self.cfg.rules,
                                   "Rules and limits"),
                                  ("course", self.cfg.course,
                                   "Course geometry"),
                                  ("build", self.cfg.build,
                                   "Build standard and modelling factors")):
            section(frame, title, r)
            r += 2
            for f in fields(obj):
                val = getattr(obj, f.name)
                if not isinstance(val, (int, float)) or isinstance(val, bool):
                    continue
                kind = int if isinstance(val, int) else float
                self.adv[(owner, f.name)] = Field(
                    frame, r, f.name, val, kind, width=11)
                r += 1
        frame.columnconfigure(1, weight=1)

    @staticmethod
    def _scrollable(parent):
        """A frame inside a scrolling canvas - the input lists are long."""
        canvas = tk.Canvas(parent, background=BG, highlightthickness=0)
        bar = ttk.Scrollbar(parent, orient="vertical", command=canvas.yview)
        frame = ttk.Frame(canvas)
        frame.bind("<Configure>",
                   lambda e: canvas.configure(scrollregion=canvas.bbox("all")))
        win = canvas.create_window((0, 0), window=frame, anchor="nw")
        canvas.bind("<Configure>",
                    lambda e: canvas.itemconfigure(win, width=e.width))
        canvas.configure(yscrollcommand=bar.set)
        canvas.pack(side="left", fill="both", expand=True)
        bar.pack(side="right", fill="y")
        canvas.bind_all("<MouseWheel>",
                        lambda e: canvas.yview_scroll(
                            int(-e.delta / 120), "units"))
        return canvas, frame

    def _build_outputs(self, parent) -> None:
        nb = ttk.Notebook(parent)
        nb.pack(fill="both", expand=True)
        self.out_nb = nb

        # --- report ---
        tab = ttk.Frame(nb)
        nb.add(tab, text="Report")
        self.txt_report = self._text(tab)

        # --- dimensions ---
        tab = ttk.Frame(nb)
        nb.add(tab, text="Dimensions")
        cols = ("quantity", "si", "imperial")
        tv = ttk.Treeview(tab, columns=cols, show="headings", height=28)
        for c, w in zip(cols, (240, 150, 210)):
            tv.heading(c, text=c.capitalize())
            tv.column(c, width=w, anchor="w")
        sb = ttk.Scrollbar(tab, orient="vertical", command=tv.yview)
        tv.configure(yscrollcommand=sb.set)
        tv.pack(side="left", fill="both", expand=True)
        sb.pack(side="right", fill="y")
        self.tv_dims = tv

        # --- charts ---
        tab = ttk.Frame(nb)
        nb.add(tab, text="Charts")
        bar = ttk.Frame(tab)
        bar.pack(fill="x", pady=3)
        ttk.Label(bar, text="chart:", font=BODY).pack(side="left", padx=4)
        self.chart_name = tk.StringVar(
            value=plots.CHART_BUILDERS[0][0])
        names = [n for n, _ in plots.CHART_BUILDERS] + ["Speeds vs weight"]
        cb = ttk.Combobox(bar, textvariable=self.chart_name, values=names,
                          state="readonly", width=32, font=BODY)
        cb.pack(side="left")
        cb.bind("<<ComboboxSelected>>", lambda e: self._draw_chart())
        self.imperial = tk.BooleanVar(value=True)
        ttk.Checkbutton(bar, text="imperial units", variable=self.imperial,
                        command=self._draw_chart).pack(side="left", padx=10)
        ttk.Button(bar, text="Export CSV",
                   command=self.export_chart_csv).pack(side="left", padx=4)
        self.chart_canvas = ChartCanvas(tab)
        self.chart_canvas.pack(fill="both", expand=True)

        # --- three view ---
        tab = ttk.Frame(nb)
        nb.add(tab, text="Three-view")
        self.three_view = ThreeViewCanvas(tab)
        self.three_view.pack(fill="both", expand=True)

        # --- scoring ---
        tab = ttk.Frame(nb)
        nb.add(tab, text="Score")
        self.txt_score = self._text(tab)

        # --- bill of materials ---
        tab = ttk.Frame(nb)
        nb.add(tab, text="Parts list")
        self.txt_bom = self._text(tab)

        # --- search log ---
        tab = ttk.Frame(nb)
        nb.add(tab, text="Search")
        self.txt_search = self._text(tab)

        # --- catalogues ---
        tab = ttk.Frame(nb)
        nb.add(tab, text="Catalogues")
        self._build_catalogues(tab)

        # --- rules ---
        tab = ttk.Frame(nb)
        nb.add(tab, text="Rules")
        bar = ttk.Frame(tab)
        bar.pack(fill="x", pady=3)
        ttk.Label(bar, text="Every requirement from the rules package that "
                            "bears on this model, and the line of source "
                            "that enforces it.", font=("Segoe UI", 8),
                  foreground="#666").pack(side="left", padx=6)
        ttk.Button(bar, text="Write RULES.md",
                   command=self.export_rules).pack(side="right", padx=6)
        self.txt_rules = self._text(tab)
        from .rulebook import as_text as rules_text
        self._set_text(self.txt_rules, rules_text())

        # --- function catalogue ---
        tab = ttk.Frame(nb)
        nb.add(tab, text="Function catalogue")
        bar = ttk.Frame(tab)
        bar.pack(fill="x", pady=3)
        ttk.Label(bar, text="filter:", font=BODY).pack(side="left", padx=4)
        self.cat_query = tk.StringVar()
        e = ttk.Entry(bar, textvariable=self.cat_query, width=30, font=BODY)
        e.pack(side="left")
        e.bind("<KeyRelease>", lambda ev: self._draw_catalogue())
        ttk.Button(bar, text="Write FUNCTIONS.md",
                   command=self.export_catalogue).pack(side="left", padx=6)
        self.txt_cat = self._text(tab)
        self._catalogue = catalogue_collect()
        self._draw_catalogue()

    def _build_catalogues(self, parent) -> None:
        """Browse the stored component data, and add to it.

        The table and the form are both generated from `CATALOGUES` in
        components.py, so a column added to a catalogue appears here
        without touching this file - and a row typed in goes through the
        same constructor as a row read from a CSV, which is why the two
        cannot disagree.
        """
        bar = ttk.Frame(parent)
        bar.pack(fill="x", pady=3)
        ttk.Label(bar, text="catalogue", font=BODY).pack(side="left", padx=6)
        self.cat_kind = tk.StringVar(value=CATALOGUES[0].key)
        cb = ttk.Combobox(bar, state="readonly", width=16, font=BODY,
                          values=[c.label for c in CATALOGUES])
        cb.set(CATALOGUES[0].label)
        cb.pack(side="left")
        cb.bind("<<ComboboxSelected>>",
                lambda e: self._select_catalogue(cb.get()))
        self.cat_combo = cb
        ttk.Button(bar, text="Reload from disk",
                   command=self._reload_catalogues).pack(side="right", padx=6)
        ttk.Button(bar, text="Open CSV location",
                   command=self._show_catalogue_path).pack(side="right")

        self.cat_note = ttk.Label(parent, text="", font=("Segoe UI", 8),
                                  foreground="#666", wraplength=900,
                                  justify="left")
        self.cat_note.pack(fill="x", padx=8, pady=(0, 4))

        table = ttk.Frame(parent)
        table.pack(fill="both", expand=True, padx=4)
        self.cat_tree = ttk.Treeview(table, show="headings", height=14)
        sb = ttk.Scrollbar(table, orient="vertical",
                           command=self.cat_tree.yview)
        self.cat_tree.configure(yscrollcommand=sb.set)
        self.cat_tree.pack(side="left", fill="both", expand=True)
        sb.pack(side="right", fill="y")
        self.cat_tree.bind("<<TreeviewSelect>>",
                           lambda e: self._catalogue_row_selected())
        # User entries are tinted so it is obvious which rows are yours
        # and which shipped with the package.
        self.cat_tree.tag_configure("user", background="#eef6ff")

        ttk.Separator(parent, orient="horizontal").pack(fill="x", pady=4)
        self.cat_form_frame = ttk.Frame(parent)
        self.cat_form_frame.pack(fill="x", padx=4, pady=(0, 4))
        self.cat_fields: Dict[str, Field] = {}

        btns = ttk.Frame(parent)
        btns.pack(fill="x", padx=8, pady=(0, 8))
        ttk.Button(btns, text="Add / update",
                   command=self._add_catalogue_entry).pack(side="left")
        ttk.Button(btns, text="Clear form",
                   command=lambda: self._fill_catalogue_form(None)).pack(
                       side="left", padx=4)
        ttk.Button(btns, text="Delete selected",
                   command=self._delete_catalogue_entry).pack(side="left",
                                                              padx=4)
        self.cat_status = ttk.Label(btns, text="", font=("Segoe UI", 8),
                                    foreground="#666")
        self.cat_status.pack(side="left", padx=10)
        self._select_catalogue(CATALOGUES[0].label)

    # ------------------------------------------------------------------
    def _spec(self):
        return CATALOGUES_BY_KEY[self.cat_kind.get()]

    def _select_catalogue(self, label: str) -> None:
        for c in CATALOGUES:
            if c.label == label:
                self.cat_kind.set(c.key)
                break
        spec = self._spec()
        # Keep the dropdown in step when the selection is made in code
        # rather than by clicking: otherwise the label and the table
        # disagree, which is exactly the kind of quiet lie this project
        # has been stripping out elsewhere.
        if self.cat_combo.get() != spec.label:
            self.cat_combo.set(spec.label)
        self.cat_note.configure(text=spec.note)
        cols = spec.fieldnames()
        self.cat_tree.configure(columns=cols)
        for c in cols:
            self.cat_tree.heading(c, text=c)
            self.cat_tree.column(c, width=max(62, min(150, 8 * len(c) + 44)),
                                 anchor="w", stretch=False)
        # rebuild the form for this catalogue's columns
        for w in self.cat_form_frame.winfo_children():
            w.destroy()
        self.cat_fields = {}
        for i, col in enumerate(spec.columns):
            r, c = divmod(i, 2)
            holder = ttk.Frame(self.cat_form_frame)
            holder.grid(row=r, column=c, sticky="ew", padx=4)
            self.cat_form_frame.columnconfigure(c, weight=1)
            self.cat_fields[col.name] = Field(holder, 0, col.name,
                                              col.default, col.kind,
                                              col.help, width=14)
            holder.columnconfigure(1, weight=1)
        self._refresh_catalogue()

    def _refresh_catalogue(self) -> None:
        spec = self._spec()
        self.cat_tree.delete(*self.cat_tree.get_children())
        n_user = 0
        for ident in sorted(spec.store):
            row = spec.to_row(spec.store[ident])
            vals = []
            for c in spec.fieldnames():
                v = row.get(c, "")
                vals.append("%.6g" % v if isinstance(v, float) else v)
            user = is_user_entry(spec.key, ident)
            n_user += bool(user)
            self.cat_tree.insert("", "end", iid=ident, values=vals,
                                 tags=("user",) if user else ())
        self.cat_status.configure(
            text="%d entries, %d of them yours (tinted)"
                 % (len(spec.store), n_user))

    def _catalogue_row_selected(self) -> None:
        sel = self.cat_tree.selection()
        if sel:
            self._fill_catalogue_form(sel[0])

    def _fill_catalogue_form(self, ident: Optional[str]) -> None:
        spec = self._spec()
        if ident is None:
            for col in spec.columns:
                self.cat_fields[col.name].set(col.default)
            return
        row = spec.to_row(spec.store[ident])
        for col in spec.columns:
            self.cat_fields[col.name].set(row.get(col.name, col.default))

    def _add_catalogue_entry(self) -> None:
        spec = self._spec()
        try:
            row = {name: fld.get() for name, fld in self.cat_fields.items()}
        except ValueError as exc:
            self.cat_status.configure(text="bad value: %s" % exc)
            return
        ident = str(row.get("key") or row.get("name") or "").strip()
        if not ident:
            self.cat_status.configure(
                text="give it a key" if "key" in self.cat_fields
                else "give it a name")
            return
        if not is_user_entry(spec.key, ident) and ident in spec.store:
            if not messagebox.askyesno(
                    "Override a built-in?",
                    "%s is a built-in %s. Your version will be used "
                    "instead, for every command, until you delete it.\n\n"
                    "Continue?" % (ident, spec.singular)):
                return
        try:
            path = add_user_entry(spec.key, row)
        except Exception as exc:
            messagebox.showerror("Could not add", str(exc))
            return
        self._refresh_catalogue()
        self.cat_tree.selection_set(ident)
        self.cat_status.configure(text="saved %s to %s"
                                       % (ident, os.path.basename(path)))
        self.status.set("%s '%s' saved - it is available to Evaluate and "
                        "to a search straight away" % (spec.singular, ident))

    def _delete_catalogue_entry(self) -> None:
        sel = self.cat_tree.selection()
        if not sel:
            self.cat_status.configure(text="select a row first")
            return
        spec, ident = self._spec(), sel[0]
        if not is_user_entry(spec.key, ident):
            self.cat_status.configure(
                text="%s is built in - only your own entries can be "
                     "deleted" % ident)
            return
        if not messagebox.askyesno("Delete", "Remove %s from %s.csv?"
                                   % (ident, spec.key)):
            return
        remove_user_entry(spec.key, ident)
        self._refresh_catalogue()
        self.cat_status.configure(text="deleted %s" % ident)

    def _reload_catalogues(self) -> None:
        counts = reload_catalogues()
        self._refresh_catalogue()
        self.cat_status.configure(
            text="reloaded: " + ", ".join("%d %s" % (v, k)
                                          for k, v in counts.items() if v)
                 or "reloaded: no user entries")

    def _show_catalogue_path(self) -> None:
        path = user_csv_path(self._spec().key)
        messagebox.showinfo(
            "Where your additions live",
            "%s\n\nEdit it by hand if you prefer, then press Reload from "
            "disk. The GUI and the file use the same columns and the same "
            "constructor, so neither can disagree with the other." % path)

    @staticmethod
    def _text(parent) -> tk.Text:
        """A scrolled, read-only text pane.

        It builds its own container and packs that into the parent, so a
        tab can hold a toolbar above it without the two geometry managers
        fighting - tkinter refuses to mix grid and pack in one widget.
        """
        holder = ttk.Frame(parent)
        holder.pack(fill="both", expand=True)
        t = tk.Text(holder, wrap="none", font=MONO, background="white",
                    relief="flat", padx=8, pady=6)
        ys = ttk.Scrollbar(holder, orient="vertical", command=t.yview)
        xs = ttk.Scrollbar(holder, orient="horizontal", command=t.xview)
        t.configure(yscrollcommand=ys.set, xscrollcommand=xs.set)
        t.grid(row=0, column=0, sticky="nsew")
        ys.grid(row=0, column=1, sticky="ns")
        xs.grid(row=1, column=0, sticky="ew")
        holder.rowconfigure(0, weight=1)
        holder.columnconfigure(0, weight=1)
        return t

    def _build_statusbar(self) -> None:
        self.status = tk.StringVar(value="ready")
        ttk.Separator(self, orient="horizontal").pack(fill="x", pady=(4, 2))
        ttk.Label(self, textvariable=self.status, font=BODY,
                  anchor="w").pack(fill="x")

    @staticmethod
    def _set_text(widget: tk.Text, text: str) -> None:
        widget.configure(state="normal")
        widget.delete("1.0", "end")
        widget.insert("1.0", text)
        widget.configure(state="disabled")

    # ------------------------------------------------------------------
    # Reading the form
    # ------------------------------------------------------------------
    def _sync_density(self) -> None:
        """Recompute density from elevation and temperature."""
        try:
            env = Environment.at_density_altitude(
                self.f_alt.get(), self.f_temp.get(), self.f_wind.get())
        except ValueError:
            self.rho_note.configure(text="")
            return
        self.f_rho.set(round(env.rho, 4))
        self._update_density_note()

    def _update_density_note(self) -> None:
        try:
            rho = self.f_rho.get()
        except ValueError:
            self.rho_note.configure(text="")
            return
        env = Environment(rho=rho)
        self.rho_note.configure(
            text="= %.0f ft density altitude, %.1f%% of sea-level ISA"
                 % (env.density_altitude_ft, 100.0 * rho / 1.225))

    def read_config(self) -> Config:
        cfg = Config()
        env = Environment.at_density_altitude(
            self.f_alt.get(), self.f_temp.get(), self.f_wind.get())
        # Viscosity still comes from the temperature - it barely depends
        # on density - but the density itself is whatever the box says,
        # so a measured value overrides the ISA estimate.
        try:
            env = Environment(rho=self.f_rho.get(), nu=env.nu,
                              wind_mps=env.wind_mps,
                              field_elev_m=env.field_elev_m)
        except ValueError:
            pass
        cfg.env = env
        for (owner, name), fld in self.adv.items():
            setattr(getattr(cfg, owner), name, fld.get())
        cfg.rules.normalisation = self.f_norm.get()
        cfg.rules.field_best_m2_lb_per_s = self.f_fm2.get()
        cfg.rules.field_best_m3_lap_lb = self.f_fm3.get()
        cfg.rules.field_best_gm_lb_in = self.f_fmg.get()
        return cfg

    def read_design(self) -> Design:
        """The design under test.

        Held as state rather than read back out of widgets: there are no
        design widgets any more.
        """
        if self.design is None:
            raise ValueError("no design loaded - run a search or Load one")
        return self.design

    @staticmethod
    def describe(d: Design) -> str:
        """One line naming an aeroplane, for the Setup panel.

        Deliberately a caption, not a readout: enough to know which
        aeroplane Evaluate will score, with the full picture left to the
        Report tab.
        """
        return ("%s   %.3f m span, AR %.2f\n%s x%d, %s, %s x%d\n"
                "sensor %.2f kg, %d simulator%s, %.0f in drop"
                % (d.airfoil, d.span_m, d.span_m / max(d.chord_m, 1e-9),
                   d.motor, d.n_motors, d.prop, d.pack, d.n_systems,
                   d.sensor_mass_kg, d.n_simulators,
                   "" if d.n_simulators == 1 else "s", d.drop_height_in))

    def write_design(self, d: Design, source: str = "edited") -> None:
        """Make `d` the design under test and say where it came from.

        The caption matters: with no design widgets, the only thing
        telling you what Evaluate is about to score is this label, so it
        names the source as well as the aeroplane.
        """
        self.design = d
        self.design_label.configure(text=self.describe(d))
        self.design_source.configure(text="from: %s" % source)
        pk = PACKS.get(d.pack)
        if pk is not None:
            self.design_source.configure(
                text="from: %s\n%s - %.1f Wh, %.0f A, %.0f g"
                     % (source, pk.name, pk.watt_hours, pk.i_max_a,
                        pk.mass_kg * 1000))

    # ------------------------------------------------------------------
    # Actions
    # ------------------------------------------------------------------
    def _invalidate(self, headline: str, detail: str = "") -> None:
        """Drop every panel that described the previous aeroplane.

        Without this the form can say one thing while the Dimensions,
        Score, Charts, Three-view and Parts list panels still show a
        complete, plausible-looking aeroplane from the last successful
        evaluation.  A stale panel that looks right is worse than an
        empty one, because nothing tells you it is stale - and switching
        chart type would redraw the OLD aircraft, since `self.aircraft`
        was still pointing at it.
        """
        # The DESIGN is still loaded - it is input, and it has not gone
        # anywhere.  Only the results computed from it are invalid, so
        # only those are dropped.  Clearing the design here would leave
        # Evaluate with nothing to retry.
        self.aircraft = None
        msg = headline + (("\n\n" + detail) if detail else "")
        self._set_text(self.txt_report, msg)
        self._set_text(self.txt_score, headline)
        self._set_text(self.txt_bom, headline)
        self.tv_dims.delete(*self.tv_dims.get_children())
        self.tv_dims.insert("", "end", values=(headline, "", ""))
        self.chart_canvas.show(None)
        self.three_view.show(None)

    def evaluate(self) -> None:
        try:
            cfg = self.read_config()
            design = self.read_design()
        except ValueError as exc:
            self.status.set("bad input: %s" % exc)
            self._invalidate("Could not evaluate.", str(exc))
            return
        # A lone design has nothing to normalise against, so score it on
        # the field estimates whatever the search mode says.  After a
        # search those estimates are the run's own population bests, which
        # _finish_search writes into the Advanced panel so they are
        # visible and editable rather than hidden in this object.
        cfg.rules.normalisation = "field"
        try:
            ac = Aircraft(design, cfg)
        except Exception as exc:
            self.status.set("failed to build")
            self._invalidate("This design could not be built.",
                             "%s\n\n%s" % (exc, traceback.format_exc()))
            return
        self.cfg, self.design, self.aircraft = cfg, design, ac

        checks = ac.static_checks()
        head = []
        if checks["ok"]:
            head.append("CONSTRAINTS: all satisfied")
        else:
            head.append("CONSTRAINTS VIOLATED:")
            for f in checks["failures"]:
                head.append("  - %s" % f)
        head.append("")
        body = capture(print_design_report, design, cfg, 1.5,
                       "DESIGN EVALUATION")
        self._set_text(self.txt_report, "\n".join(head) + body)
        self._set_text(self.txt_bom, capture(print_bom, design, cfg))

        self.tv_dims.delete(*self.tv_dims.get_children())
        for row in plots.dimensions(ac):
            self.tv_dims.insert("", "end", values=row)

        self._draw_chart()
        self.three_view.show(ac)

        try:
            card = evaluate_scores(ac, cfg, 1.5)
            self._set_text(self.txt_score,
                           score_explanation_text(ac, cfg, card))
            self.status.set(
                "%s   |   M2 %.3f  M3 %.3f  total %.3f   |   %.1f lb gross, "
                "%.1f Wh, %s"
                % ("OK" if checks["ok"] else "INFEASIBLE",
                   card.m2, card.m3, card.total_mission,
                   ac.mtow_m2_kg * KG2LB, ac.total_watt_hours,
                   "structure OK" if ac.structure_ok else "SPAR WILL NOT CLOSE"))
        except Exception as exc:
            # The aeroplane built, so the geometry panels are valid; only
            # the score is not.  Say that precisely rather than blanking
            # panels that are still telling the truth.
            self._set_text(self.txt_score,
                           "This design was built, but could not be "
                           "scored:\n\n%s\n\nThe dimensions, charts and "
                           "three-view above are still valid; the score "
                           "is not." % exc)
            self.status.set("built, but scoring failed: %s" % exc)

    def _draw_chart(self) -> None:
        if self.aircraft is None:
            return
        name = self.chart_name.get()
        imp = self.imperial.get()
        try:
            if name == "Speeds vs weight":
                chart = plots.weight_sweep(self.aircraft, self.cfg,
                                           imperial=imp)
            else:
                fn = dict(plots.CHART_BUILDERS)[name]
                chart = fn(self.aircraft, imperial=imp)
        except Exception as exc:
            self.status.set("chart failed: %s" % exc)
            return
        self.chart_canvas.show(chart)

    def _draw_catalogue(self) -> None:
        q = self.cat_query.get()
        entries = [e for e in self._catalogue if e.matches(q)]
        self._set_text(self.txt_cat, catalogue_text(entries))

    def export_rules(self) -> None:
        from .rulebook import as_markdown as rules_markdown
        path = filedialog.asksaveasfilename(
            defaultextension=".md", initialfile="RULES.md",
            filetypes=[("Markdown", "*.md")])
        if not path:
            return
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(rules_markdown())
        self.status.set("wrote %s" % path)

    def export_catalogue(self) -> None:
        from .catalogue import as_markdown
        path = filedialog.asksaveasfilename(
            defaultextension=".md", initialfile="FUNCTIONS.md",
            filetypes=[("Markdown", "*.md")])
        if not path:
            return
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(as_markdown(self._catalogue))
        self.status.set("wrote %s" % path)

    def export_chart_csv(self) -> None:
        if self.chart_canvas.chart is None:
            return
        path = filedialog.asksaveasfilename(
            defaultextension=".csv", filetypes=[("CSV", "*.csv")])
        if not path:
            return
        ch = self.chart_canvas.chart
        import csv
        with open(path, "w", newline="", encoding="utf-8") as fh:
            w = csv.writer(fh)
            w.writerow([ch.title])
            for s in ch.series:
                w.writerow([])
                w.writerow([s.label])
                w.writerow([ch.x_label, ch.y_label])
                for x, y in zip(s.xs, s.ys):
                    w.writerow(["%.6g" % x, "%.6g" % y])
        self.status.set("wrote %s" % path)

    def load_design(self) -> None:
        path = filedialog.askopenfilename(filetypes=[("JSON", "*.json")])
        if not path:
            return
        try:
            with open(path, encoding="utf-8") as fh:
                data = json.load(fh)
            known = {f.name for f in fields(Design)}
            self.write_design(Design(**{k: v for k, v in data.items()
                                        if k in known}),
                              os.path.basename(path))
        except Exception as exc:
            messagebox.showerror("Could not load", str(exc))
            return
        self.evaluate()

    def save_design(self) -> None:
        path = filedialog.asksaveasfilename(
            defaultextension=".json", filetypes=[("JSON", "*.json")])
        if not path:
            return
        d = self.read_design()
        with open(path, "w", encoding="utf-8") as fh:
            json.dump({f.name: getattr(d, f.name) for f in fields(Design)},
                      fh, indent=2)
        self.status.set("wrote %s" % path)

    def reset_defaults(self) -> None:
        base = Config()
        for (owner, name), fld in self.adv.items():
            fld.set(getattr(getattr(base, owner), name))
        self.status.set("advanced values reset to defaults")

    # ------------------------------------------------------------------
    # Search on a worker thread
    # ------------------------------------------------------------------
    def run_search(self) -> None:
        if self.search_thread and self.search_thread.is_alive():
            self.status.set("a search is already running")
            return
        try:
            cfg = self.read_config()
            space = self.read_space()
        except ValueError as exc:
            self.status.set("bad input: %s" % exc)
            return
        mode = self.search_mode.get()
        settings = (SearchSettings.quick() if mode == "quick" else
                    SearchSettings.thorough() if mode == "thorough" else
                    SearchSettings())
        self.out_nb.select(6)                      # show the search log
        bounds = space.continuous_bounds(cfg)
        self._search_header = (
                       "running the %s search...\n"
                       "This takes minutes and uses every core. The window "
                       "stays responsive; results land here when it "
                       "finishes.\n\n"
                       "Searching, from the Search space tab:\n"
                       "  span         %.2f to %.2f m\n"
                       "  aspect ratio %.1f to %.1f\n"
                       "  taper        %.2f to %.2f\n"
                       "  sensor       %.2f to %.2f kg\n"
                       "  M3 fraction  %.2f to %.2f\n"
                       "  drop height  %.0f to %.0f in\n"
                       "  motors %s, propulsion systems %s\n"
                       % (mode, bounds[0][0], bounds[0][1],
                          bounds[1][0], bounds[1][1],
                          bounds[4][0], bounds[4][1],
                          bounds[2][0], bounds[2][1],
                          bounds[3][0], bounds[3][1],
                          bounds[5][0], bounds[5][1],
                          space.motor_counts, space.system_counts))
        self._set_text(self.txt_search, self._search_header)
        self.search_btn.configure(state="disabled")
        self.status.set("searching (%s)..." % mode)

        def work():
            try:
                buf = io.StringIO()
                with redirect_stdout(buf):
                    res = optimise(cfg, space, settings, verbose=True)
                self.search_q.put(("done", (res, cfg, buf.getvalue())))
            except Exception:
                self.search_q.put(("error", traceback.format_exc()))

        self.search_thread = threading.Thread(target=work, daemon=True)
        self.search_thread.start()

    def _poll_search(self) -> None:
        try:
            while True:
                kind, payload = self.search_q.get_nowait()
                if kind == "error":
                    self._set_text(self.txt_search,
                                   getattr(self, "_search_header", "")
                                   + "\n" + payload)
                    self.status.set("search failed")
                elif kind == "done":
                    res, cfg, log = payload
                    self._finish_search(res, cfg, log)
                self.search_btn.configure(state="normal")
        except queue.Empty:
            pass
        self._after_ids.append(self.after(150, self._poll_search))
        # Keep only the live handle; the list is otherwise unbounded over
        # a long session.
        self._after_ids = self._after_ids[-4:]

    def _finish_search(self, res, cfg, log: str) -> None:
        if not res.ranked:
            self._set_text(self.txt_search,
                           log + "\nNothing feasible. Loosen a limit.")
            self.status.set("search found nothing feasible")
            return
        from .report import print_pareto, print_ranking
        text = log
        text += capture(print_ranking, res.ranked, 12,
                        "TOP DESIGNS (%s-normalised)" % res.mode)
        text += capture(print_pareto, res.pareto)
        # Keep the space that produced this result at the top of the log:
        # a ranking is meaningless without knowing what was searched.
        self._set_text(self.txt_search,
                       getattr(self, "_search_header", "") + "\n" + text)

        # The search ranked its finalists against the best raw scores it
        # found.  Write those into the Advanced panel so that re-scoring
        # the winner here gives the SAME number the ranking did, instead
        # of quietly falling back to the default field estimates - and so
        # the normalisers are visible and editable rather than held in a
        # private attribute.  Getting this wrong once already made the
        # sensitivity table print scores above the ceiling.
        for name, value in (("field_best_m2_lb_per_s", res.ref_m2),
                            ("field_best_m3_lap_lb", res.ref_m3),
                            ("field_best_gm_lb_in", res.ref_gm)):
            fld = self.adv.get(("rules", name))
            if fld is not None and value:
                fld.set(value)

        best = res.ranked[0]["design"]
        self.write_design(best, "best of the %s search (%d designs)"
                          % (res.mode, res.n_evaluated))
        self.status.set("search finished: %d designs evaluated, best loaded "
                        "into the form; normalisers updated from the run"
                        % res.n_evaluated)
        self.evaluate()
        self.out_nb.select(0)


def main(argv: Optional[List[str]] = None) -> int:
    # Windows starts worker processes by re-importing __main__.  If the
    # script that launched this GUI has no `if __name__ == "__main__":`
    # guard, every worker the search spawns would open its own window and
    # start its own search.  The supplied launchers are guarded; this
    # turns an unguarded one into a clear message instead of a swarm.
    import multiprocessing
    if multiprocessing.current_process().name != "MainProcess":
        raise RuntimeError(
            "dbf2027.gui.main() was called inside a worker process. The "
            "script that launches the GUI needs an "
            "`if __name__ == \"__main__\":` guard - see dbf_gui.py.")
    root = tk.Tk()
    try:
        ttk.Style().theme_use("vista")
    except tk.TclError:
        pass
    App(root)
    root.mainloop()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
